development:
  project_id: 455451
  project_name: Training Project
  iteration_seed: 2012/01/16 00:00:00 UTC
  iteration_length: 1
  username: admin
  hash_password: "$2a$10$yj/TB.w.HRiFvUuHs.uaAuD64QGMCrBJIl6fq5MuDuj3qNDrjjhq6"
  proxy: auto
  bucket_code: ''
  page_size: 3000
  pt_api: 'http://www.pivotaltracker.com/services/v3/projects/'
    
test:
  project_id: 466613
  project_name: Test Project
  iteration_seed: 2012/01/16 00:00:00 UTC
  iteration_length: 1
  test_ticket_id: 24235441
  test_ticket_name: New Story
  username: admin
  hash_password: "$2a$10$yj/TB.w.HRiFvUuHs.uaAuD64QGMCrBJIl6fq5MuDuj3qNDrjjhq6"
  proxy: auto
  bucket_code: 'bucket'
  page_size: 3000
  pt_api: 'http://www.pivotaltracker.com/services/v3/projects/'
  
production:
  proxy: auto
  page_size: 3000
  pt_api: 'http://www.pivotaltracker.com/services/v3/projects/'
