development:
  project_id: 466613
  project_name: LIMS - core redesign
  iteration_length: 2
  username: admin
  hash_password: "$2a$10$yj/TB.w.HRiFvUuHs.uaAuD64QGMCrBJIl6fq5MuDuj3qNDrjjhq6"
  proxy: auto
  bucket_code: ''
  page_size: 3000
  pt_api: 'http://www.pivotaltracker.com/services/v3/projects/'
    
test:
  project_id: 466613
  project_name: LIMS - core redesign
  iteration_length: 2
  test_ticket_id: 24235441
  test_ticket_name: New Story
  username: admin
  hash_password: "$2a$10$yj/TB.w.HRiFvUuHs.uaAuD64QGMCrBJIl6fq5MuDuj3qNDrjjhq6"
  proxy: auto
  bucket_code: 'bucket'
  page_size: 3000
  pt_api: 'http://www.pivotaltracker.com/services/v3/projects/'