development:
  adapter: mysql
  database: pt_stories
  username: root
  password:
  port: 3306
  
test:
  adapter: mysql
  database: pt_stories
  username: root
  password:
  port: 3306
  
production:
  adapter: postgresql
  encoding: unicode